### ISSUE TITLE
Support x-www-form-urlencoded body without template

### ISSUE THREAD

**Issue by ernilsson** [ernilsson/pia#16]
Shall be able to add form bodies without going through the hassle of placing it in a file ready to be shipped off. A typical use-case could look like the below:

```yml
request:
  body:
    form:
      grant_type: password
      username: ${profile.username}
      password: ${profile.password}
```

Shall be implemented as part of the Pia core, not as a plugin as supporting a wider variety of HTTP standards should be a goal for the core application. 

If more than one body specification is provided in the request configuration an error should be returned, there is no order of precedence. 

An example of an erroneous request configuration is given below. 

```yml
request:
  body:
    file: tmpl.form
    form:
      grant_type: password
      username: ${profile.username}
      password: ${profile.password}
```
